name: billar_control_pro
description: Sistema de control para billar con una central y cinco mesas.
publish_to: "none"
version: 2.0.0+45

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
