name: billar_control_pro
description: Billar Control Pro - sistema central y 5 mesas.
publish_to: 'none'
version: 3.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.5.3

flutter:
  uses-material-design: true
